name: test

on: [push, pull_request]
env:
  EMACS: /home/runner/.nix-profile/bin/emacs
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs-version: [27.1, 29.4, snapshot]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Set up Emacs
      uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}
    - name: Install Pymacs
      run: |
        cd /home/runner/work
        git clone https://github.com/mlt/Pymacs
        cd Pymacs
        make check EMACS=$EMACS
        sudo make install EMACS=$EMACS
        sudo cp pymacs.el /home/runner/.nix-profile/share/emacs/site-lisp/
    - name: Install ropemacs
      run: |
        python -m pip install --user --editable .
    - name: Test ropemacs
      run: emacs -batch -l ert -l test_emacs.el -f ert-run-tests-batch-and-exit
